template = ""
rev_id = 4
template_sha = "87be02986858c4b7ae5e8613b6f951c3c209b221"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "so"
__UND2C_TRG__ = "fi"
__UNDEFINED_SOURCE__ = "Somali"
__UNDEFINED_TARGET__ = "Finnish"
__UND_SRC__ = "som"
__UND_TRG__ = "fin"
